---
- name: setup repo
  template:
    src: elastic.repo.j2
    dest: /etc/yum.repos.d/elastic.repo
    owner: root
    group: root
    mode: '0644'
- name: configure ElasticSearch yml
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: '0660'
- name: configure ElasticSearch Java Parameters
  template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options 
    owner: root
    group: elasticsearch
    mode: '0660'
- name: configure ElasticSearch 
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/elasticsearch.service.d/override.conf 
    owner: root
    group: root
    mode: '0644'
- name: install elasticsearch
  yum:
    name: elasticsearch
    state: present